# Generated by Django 4.2.10 on 2024-02-29 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'دپارتمان',
                'verbose_name_plural': 'دپارتمان\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('model', models.CharField(max_length=255, verbose_name='مدل')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='تولید کننده')),
                ('purchase_date', models.CharField(max_length=255, verbose_name='تاریخ خرید')),
                ('warranty_period', models.CharField(max_length=255, verbose_name='مدت ضمانت')),
                ('serial_number', models.CharField(max_length=255, verbose_name='شماره سریال')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=10, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'دستگاه',
                'verbose_name_plural': 'دستگاه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('name_en', models.CharField(max_length=255, verbose_name='Name')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.device', verbose_name='دستگاه')),
            ],
            options={
                'verbose_name': 'آزمایش',
                'verbose_name_plural': 'آزمایش\u200cها',
            },
        ),
        migrations.CreateModel(
            name='LabType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'نوع آزمایشگاه',
                'verbose_name_plural': 'انواع آزمایشگاه',
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.experiment', verbose_name='آزمایش')),
            ],
            options={
                'verbose_name': 'پارامتر',
                'verbose_name_plural': 'پارامترها',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('done', 'Done'), ('canceled', 'Canceled')], max_length=10, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روز رسانی')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lab.experiment', verbose_name='آزمایش')),
                ('parameter', models.ManyToManyField(to='lab.parameter', verbose_name='پارامتر')),
            ],
            options={
                'verbose_name': 'درخواست',
                'verbose_name_plural': 'درخواست\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('name_en', models.CharField(max_length=255, verbose_name='Name')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('phone_number', models.CharField(max_length=255, verbose_name='شماره تلفن')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lab.department', verbose_name='دپارتمان')),
                ('device', models.ManyToManyField(to='lab.device', verbose_name='دستگاه')),
                ('lab_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lab.labtype', verbose_name='نوع آزمایشگاه')),
            ],
            options={
                'verbose_name': 'آزمایشگاه',
                'verbose_name_plural': 'آزمایشگاه\u200cها',
            },
        ),
        migrations.AddField(
            model_name='experiment',
            name='laboratory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.laboratory', verbose_name='آزمایشگاه'),
        ),
    ]
