# Generated by Django 4.2.10 on 2024-03-05 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='device',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='تولید کننده'),
        ),
        migrations.AlterField(
            model_name='device',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='مدل'),
        ),
        migrations.AlterField(
            model_name='device',
            name='purchase_date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='تاریخ خرید'),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره سریال'),
        ),
        migrations.AlterField(
            model_name='device',
            name='warranty_period',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='مدت ضمانت'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.device', verbose_name='دستگاه'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='device',
            field=models.ManyToManyField(blank=True, null=True, to='lab.device', verbose_name='دستگاه'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='lab_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lab.labtype', verbose_name='نوع آزمایشگاه'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='labtype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
