# Generated by Django 4.2.10 on 2024-03-07 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_alter_department_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='lab.device', verbose_name='دستگاه'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='laboratory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='lab.laboratory', verbose_name='آزمایشگاه'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='device',
            field=models.ManyToManyField(blank=True, to='lab.device', verbose_name='دستگاه'),
        ),
    ]
