# Generated by Django 4.2.10 on 2024-03-08 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lab', '0003_laboratory_description_laboratory_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='operator',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'staff'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='op_laboratories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('hidden', 'Hidden')], default='active', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='technical_manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'staff'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tm_laboratories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parameter',
            name='unit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='واحد'),
        ),
        migrations.AddField(
            model_name='request',
            name='owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'staff'}, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='درخواست کننده'),
        ),
        migrations.AddField(
            model_name='request',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laboratories', to='lab.department', verbose_name='دپارتمان'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='lab_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laboratories', to='lab.labtype', verbose_name='نوع آزمایشگاه'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('done', 'Done'), ('canceled', 'Canceled')], default='pending', max_length=10, null=True, verbose_name='وضعیت'),
        ),
    ]
