# Generated by Django 4.2.10 on 2024-03-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_experiment_form_alter_request_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='response_json',
            field=models.JSONField(blank=True, null=True, verbose_name='پاسخ'),
        ),
    ]
