# Generated by Django 4.2.10 on 2024-03-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0007_formresponse_response_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تحویل'),
        ),
        migrations.AddField(
            model_name='request',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='request',
            name='request_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره درخواست'),
        ),
        migrations.AddField(
            model_name='request',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='موضوع درخواست'),
        ),
    ]
