# Generated by Django 4.2.10 on 2024-03-14 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_request_delivery_date_request_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='form_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره نمونه'),
        ),
        migrations.AlterField(
            model_name='formresponse',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formresponse', to='lab.request', verbose_name='درخواست'),
        ),
    ]
