# Generated by Django 4.2.10 on 2024-03-15 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lab', '0009_formresponse_form_number_alter_formresponse_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formresponse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به روز رسانی'),
        ),
        migrations.AlterField(
            model_name='request',
            name='owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'customer'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to=settings.AUTH_USER_MODEL, verbose_name='درخواست کننده'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('done', 'Done'), ('canceled', 'Canceled')], default='new', max_length=10, null=True, verbose_name='وضعیت'),
        ),
    ]
