# Generated by Django 4.2.10 on 2024-03-15 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lab', '0010_formresponse_created_at_formresponse_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='application',
            field=models.TextField(blank=True, null=True, verbose_name='کاربرد'),
        ),
        migrations.AddField(
            model_name='device',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='شرح خدمات'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='operator',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'staff'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='op_experiments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experiment',
            name='test_unit_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع واحد آزمون'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='work_scope',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='گستره کاری'),
        ),
    ]
