# Generated by Django 4.2.10 on 2024-04-04 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lab', '0011_device_application_device_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام گردش کار')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال بودن')),
            ],
            options={
                'verbose_name': 'گردش کار',
                'verbose_name_plural': 'گردش کارها',
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مرحله')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='مهلت')),
                ('progress', models.IntegerField(default=0, verbose_name='پیشرفت')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر اختصاص یافته')),
                ('next_step', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_step', to='lab.workflowstep', verbose_name='مرحله بعدی')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='lab.workflow', verbose_name='گردش کار')),
            ],
            options={
                'verbose_name': 'مرحله گردش کار',
                'verbose_name_plural': 'مراحل گردش کار',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(blank=True, default=False, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_status', to='lab.request', verbose_name='درخواست')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lab.workflowstep')),
            ],
        ),
    ]
