# Generated by Django 4.2.10 on 2024-04-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0013_status_accept_status_action_by_status_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='is_first_step',
            field=models.BooleanField(default=False, verbose_name='مرحله اول'),
        ),
    ]
