# Generated by Django 4.2.10 on 2024-04-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0014_workflowstep_is_first_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowstep',
            name='deadline',
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='next_button_color',
            field=models.CharField(choices=[('info', 'Info'), ('paper', 'Paper'), ('secondary', 'Secondary'), ('secondary_light', 'Secondary_light'), ('success', 'Success'), ('error', 'Error'), ('warning', 'Warning'), ('primary', 'Primary'), ('black', 'Black')], default='info', max_length=20, verbose_name='رنگ دکمه تایید'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='next_button_title',
            field=models.CharField(default='تایید', max_length=100, verbose_name='نام دکمه تایید'),
        ),
    ]
