# Generated by Django 4.2.10 on 2024-04-10 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0015_remove_workflowstep_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='step_status', to='lab.workflowstep'),
        ),
    ]
