# Generated by Django 4.2.10 on 2024-04-12 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0016_alter_status_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStepButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_slug', models.CharField(choices=[('next_step', 'Next Step'), ('previous_step', 'Previous Step'), ('reject_step', 'Reject Step'), ('view_result', 'View Result'), ('print_result', 'Print Result'), ('upload_result', 'Upload Result')], default='print_result', max_length=20, verbose_name='کد عملگر')),
                ('title', models.CharField(default='نام دکمه', max_length=100, verbose_name='نام دکمه')),
                ('color', models.CharField(choices=[('info', 'Info'), ('paper', 'Paper'), ('secondary', 'Secondary'), ('secondary_light', 'Secondary_light'), ('success', 'Success'), ('error', 'Error'), ('warning', 'Warning'), ('primary', 'Primary'), ('black', 'Black')], default='info', max_length=20, verbose_name='رنگ دکمه')),
            ],
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'وضعیت درخواست', 'verbose_name_plural': 'وضعیت های درخواست'},
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='has_next_step',
            field=models.BooleanField(default=False, verbose_name='مرحله بعد دارد'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='has_reject_step',
            field=models.BooleanField(default=False, verbose_name='رد شدن دارد'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='reject_button_color',
            field=models.CharField(blank=True, choices=[('info', 'Info'), ('paper', 'Paper'), ('secondary', 'Secondary'), ('secondary_light', 'Secondary_light'), ('success', 'Success'), ('error', 'Error'), ('warning', 'Warning'), ('primary', 'Primary'), ('black', 'Black')], default='info', max_length=20, null=True, verbose_name='رنگ دکمه رد'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='reject_button_title',
            field=models.CharField(blank=True, default='رد', max_length=100, null=True, verbose_name='نام دکمه رد'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='reject_step',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.workflowstep', verbose_name='مرحله رد'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='button',
            field=models.ManyToManyField(to='lab.workflowstepbutton', verbose_name='دکمه'),
        ),
    ]
