# Generated by Django 4.2.10 on 2024-04-12 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0017_workflowstepbutton_alter_status_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowstepbutton',
            options={'verbose_name': 'دکمه مرحله گردش کار', 'verbose_name_plural': 'دکمه های مرحله گردش کار'},
        ),
    ]
