# Generated by Django 4.2.10 on 2024-04-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0018_alter_workflowstepbutton_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='unit',
            field=models.IntegerField(blank=True, default=1, help_text='مقدار عددی بر حسب نمونه، مبنای محاسبه قیمت', max_length=255, null=True, verbose_name='واحد'),
        ),
    ]
