# Generated by Django 4.2.10 on 2024-04-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0019_alter_parameter_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام انگلیسی'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='unit_value',
            field=models.IntegerField(blank=True, default=1, help_text='مقدار عددی بر حسب نمونه، مبنای محاسبه قیمت', max_length=255, null=True, verbose_name='مقدار واحد'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='name_en',
            field=models.CharField(max_length=255, verbose_name='نام انگلیسی'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='unit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='واحد'),
        ),
    ]
