# Generated by Django 4.2.10 on 2024-04-16 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0020_parameter_name_en_parameter_unit_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstep',
            name='next_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_step', to='lab.workflowstep', verbose_name='مرحله بعدی'),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='reject_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.workflowstep', verbose_name='مرحله رد'),
        ),
    ]
