# Generated by Django 4.2.10 on 2024-05-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0021_alter_workflowstep_next_step_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='unit_value',
            field=models.IntegerField(blank=True, default=1, help_text='مقدار عددی بر حسب نمونه، مبنای محاسبه قیمت', null=True, verbose_name='مقدار واحد'),
        ),
    ]
