# Generated by Django 4.2.10 on 2024-05-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0023_experiment_rules_laboratory_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='urgent_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='قیمت فوری'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='unit',
            field=models.CharField(blank=True, choices=[('sample', 'نمونه'), ('time', 'زمان')], max_length=25, null=True, verbose_name='واحد'),
        ),
    ]
