# Generated by Django 4.2.10 on 2024-05-23 07:52

import apps.lab.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0026_experiment_estimated_result_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.lab.models.request_result_directory_path, verbose_name='فایل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_results', to='lab.request', verbose_name='درخواست')),
            ],
            options={
                'verbose_name': 'نتیجه درخواست',
                'verbose_name_plural': 'نتایج درخواست\u200cها',
            },
        ),
    ]
