# Generated by Django 4.2.10 on 2024-05-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0027_requestresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='status',
        ),
        migrations.AddField(
            model_name='request',
            name='is_completed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='تکمیل شده'),
        ),
    ]
