# Generated by Django 4.2.10 on 2024-07-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0029_experiment_estimated_urgent_result_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='discount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
