# Generated by Django 4.2.10 on 2024-07-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0030_request_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstepbutton',
            name='action_slug',
            field=models.CharField(choices=[('next_step', 'Next Step'), ('previous_step', 'Previous Step'), ('reject_step', 'Reject Step'), ('view_result', 'View Result'), ('print_result', 'Print Result'), ('upload_result', 'Upload Result'), ('request_discount', 'Request Discount')], default='print_result', max_length=20, verbose_name='کد عملگر'),
        ),
    ]
