# Generated by Django 4.2.10 on 2024-08-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0031_alter_workflowstepbutton_action_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='add_telephone1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='داخلی'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='add_telephone2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='داخلی'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='response_hours',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ساعت پاسخگویی'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='telephone1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره تلفن'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='telephone2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره همراه'),
        ),
    ]
