# Generated by Django 4.2.10 on 2024-08-12 07:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lab', '0032_laboratory_add_telephone1_laboratory_add_telephone2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='operators',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'staff'}, null=True, related_name='ops_laboratories', to=settings.AUTH_USER_MODEL),
        ),
    ]
