# Generated by Django 4.2.10 on 2024-08-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0033_laboratory_operators'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='discount_description',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='توضیحات تخفیف'),
        ),
    ]
