# Generated by Django 4.2.10 on 2024-08-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0034_request_discount_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_returned',
            field=models.BooleanField(default=False, verbose_name='عودت شده'),
        ),
    ]
