# Generated by Django 4.2.10 on 2024-08-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0035_request_is_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='is_main',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='اصلی'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='response_count',
            field=models.IntegerField(default=0, verbose_name='تعداد پاسخ\u200cها'),
        ),
    ]
