# Generated by Django 4.2.10 on 2024-08-26 07:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lab', '0036_formresponse_is_main_formresponse_response_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='operators',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'staff'}, related_name='ops_laboratories', to=settings.AUTH_USER_MODEL),
        ),
    ]
