# Generated by Django 4.2.10 on 2024-08-26 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0037_alter_laboratory_operators'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(verbose_name='تاریخ صدور')),
                ('temperature', models.CharField(max_length=5, verbose_name='دما (درجه سانتی\u200cگراد)')),
                ('humidity', models.CharField(max_length=5, verbose_name='رطوبت (%)')),
                ('pressure', models.CharField(max_length=5, verbose_name='فشار (میلی\u200cبار)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روز رسانی')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='lab.request', verbose_name='درخواست')),
            ],
            options={
                'verbose_name': 'گواهی درخواست',
                'verbose_name_plural': 'گواهی\u200cهای درخواست',
            },
        ),
    ]
