# Generated by Django 4.2.10 on 2024-08-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0038_requestcertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='economic_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره اقتصادی'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='fax',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='دورنگار'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شناسه ملی'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد پستی'),
        ),
    ]
