# Generated by Django 4.2.10 on 2024-08-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0039_laboratory_economic_number_laboratory_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='accuracy',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='دقت دستگاه'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='کد دستگاه'),
        ),
    ]
