# Generated by Django 4.2.10 on 2024-08-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0040_device_accuracy_device_device_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='control_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='کد کنترلی'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='has_iso_17025',
            field=models.BooleanField(default=False),
        ),
    ]
