# Generated by Django 4.2.10 on 2024-08-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0041_laboratory_control_code_laboratory_has_iso_17025'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='commissioning_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ راه\u200cاندازی دستگاه'),
        ),
        migrations.AddField(
            model_name='device',
            name='control_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='کد کنترلی دستگاه'),
        ),
        migrations.AddField(
            model_name='device',
            name='country_of_manufacture',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='کشور سازنده'),
        ),
        migrations.AddField(
            model_name='device',
            name='extra_status',
            field=models.CharField(choices=[('operational', 'سالم'), ('under_repair', 'در حال تعمیر'), ('commissioning', 'در حال راه\u200cاندازی'), ('calibration', 'در حال کالیبراسیون'), ('awaiting_budget', 'در انتظار بودجه برای تعمیر'), ('decommissioned', 'به طور کامل از کار افتاده')], default='operational', max_length=20, verbose_name='وضعیت اضافی'),
        ),
        migrations.AddField(
            model_name='device',
            name='labsnet_device_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شناسه نوع دستگاه در شبکه راهبردی'),
        ),
        migrations.AddField(
            model_name='device',
            name='labsnet_model_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شناسه مدل دستگاه در شبکه راهبردی'),
        ),
        migrations.AddField(
            model_name='device',
            name='manufacturer_representation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نمایندگی شرکت سازنده'),
        ),
    ]
