# Generated by Django 4.2.10 on 2024-08-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0043_experiment_control_code_experiment_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='copy_check',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='چک کپی'),
        ),
        migrations.AddField(
            model_name='request',
            name='sample_check',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='چک نمونه'),
        ),
    ]
