# Generated by Django 4.2.10 on 2024-08-29 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0044_formresponse_copy_check_request_sample_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formresponse',
            name='response_count',
            field=models.IntegerField(default=1, verbose_name='تعداد پاسخ\u200cها'),
        ),
    ]
