# Generated by Django 4.2.10 on 2024-09-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0045_alter_formresponse_response_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='تکمیل شده'),
        ),
        migrations.AlterField(
            model_name='request',
            name='sample_check',
            field=models.BooleanField(default=False, verbose_name='چک نمونه'),
        ),
    ]
