# Generated by Django 4.2.10 on 2024-09-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0046_alter_request_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_sample_returned',
            field=models.BooleanField(default=False, verbose_name='عودت نمونه'),
        ),
        migrations.AlterField(
            model_name='request',
            name='is_returned',
            field=models.BooleanField(default=False, verbose_name='مبلغ عودت شده'),
        ),
    ]
