# Generated by Django 4.2.10 on 2024-09-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0048_requestresult_result_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='partner_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='قیمت همکار'),
        ),
    ]
