# Generated by Django 4.2.10 on 2024-09-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0049_parameter_partner_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='لغو شده'),
        ),
    ]
