# Generated by Django 4.2.10 on 2024-09-22 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0050_request_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_form_response', to='lab.formresponse', verbose_name='نمونه مادر'),
        ),
    ]
