# Generated by Django 4.2.10 on 2024-09-28 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0052_request_price_wod_discounthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='price_sample_returned',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='قیمت'),
        ),
    ]
