# Generated by Django 4.2.10 on 2024-10-01 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0053_request_price_sample_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='has_parent_request',
            field=models.BooleanField(default=False, verbose_name='درخواست اصلی'),
        ),
        migrations.AddField(
            model_name='request',
            name='parent_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_requests', to='lab.request', verbose_name='درخواست مادر'),
        ),
    ]
