# Generated by Django 4.2.10 on 2024-10-01 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0054_request_has_parent_request_request_parent_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowstep',
            name='next_button_color',
        ),
        migrations.RemoveField(
            model_name='workflowstep',
            name='next_button_title',
        ),
        migrations.RemoveField(
            model_name='workflowstep',
            name='reject_button_color',
        ),
        migrations.RemoveField(
            model_name='workflowstep',
            name='reject_button_title',
        ),
    ]
