# Generated by Django 4.2.10 on 2024-10-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0055_remove_workflowstep_next_button_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='step_color',
            field=models.CharField(choices=[('info', 'Info'), ('paper', 'Paper'), ('secondary', 'Secondary'), ('secondary_light', 'Secondary_light'), ('success', 'Success'), ('error', 'Error'), ('warning', 'Warning'), ('primary', 'Primary'), ('black', 'Black')], default='info', max_length=20, verbose_name='رنگ دکمه تایید'),
        ),
    ]
