# Generated by Django 4.2.10 on 2024-10-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0056_workflowstep_step_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='labsnet',
            field=models.BooleanField(default=False, verbose_name='اعتبار لبزنت'),
        ),
        migrations.AlterField(
            model_name='request',
            name='has_parent_request',
            field=models.BooleanField(default=False, verbose_name='درخواست مادر دارد'),
        ),
        migrations.AlterField(
            model_name='request',
            name='price_sample_returned',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='قیمت ارسال نمونه'),
        ),
        migrations.AlterField(
            model_name='request',
            name='price_wod',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='قیمت بدون تخفیف'),
        ),
    ]
