# Generated by Django 4.2.10 on 2024-10-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0057_request_labsnet_alter_request_has_parent_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='labsnet_discount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='تخفیف لبزنت'),
        ),
    ]
