# Generated by Django 4.2.10 on 2024-10-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0058_request_labsnet_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='labsnet_code1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد لبزنت ۱'),
        ),
        migrations.AddField(
            model_name='request',
            name='labsnet_code2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد لبزنت ۲'),
        ),
    ]
