# Generated by Django 4.2.10 on 2024-11-03 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lab', '0059_request_labsnet_code1_request_labsnet_code2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to=settings.AUTH_USER_MODEL, verbose_name='درخواست کننده'),
        ),
    ]
