# Generated by Django 4.2.10 on 2024-11-03 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_alter_department_options'),
        ('lab', '0060_alter_request_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='grant_request1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gr_request1', to='account.grantrequest'),
        ),
        migrations.AddField(
            model_name='request',
            name='grant_request2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gr_request2', to='account.grantrequest'),
        ),
    ]
