# Generated by Django 4.2.10 on 2024-11-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0061_request_grant_request1_request_grant_request2'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='grant_request_discount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='تخفیف پژوهشی'),
        ),
    ]
