# Generated by Django 4.2.10 on 2024-11-12 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_alter_department_options'),
        ('lab', '0064_alter_request_labsnet_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='labsnet_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='توضیحات گرنت لبزنت'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='role_assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.role', verbose_name='نقش موثر'),
        ),
    ]
