# Generated by Django 4.2.10 on 2024-12-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0065_request_labsnet_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='partner_urgent_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='قیمت فوری همکار'),
        ),
    ]
