# Generated by Django 4.2.10 on 2024-12-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0067_alter_request_labsnet_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='labsnet_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ثبت نشده'), (2, 'ثبت موفق'), (3, 'ثبت ناموفق')], default=1, null=True, verbose_name='وضعیت ثبت لبزنت'),
        ),
    ]
