# Generated by Django 4.2.10 on 2025-01-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0069_grantrequesttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='test_duration',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
