# Generated by Django 4.2.10 on 2025-01-03 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0070_request_test_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='is_visible_iso',
            field=models.BooleanField(default=False),
        ),
    ]
