# Generated by Django 4.2.10 on 2025-01-18 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_labsnetcredit'),
        ('lab', '0071_laboratory_is_visible_iso'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='labsnet1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ln_request1', to='account.labsnetcredit', verbose_name='کد لبزنت ۱'),
        ),
        migrations.AddField(
            model_name='request',
            name='labsnet2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ln_request2', to='account.labsnetcredit', verbose_name='کد لبزنت ۲'),
        ),
    ]
