# Generated by Django 4.2.10 on 2025-01-18 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0072_request_labsnet1_request_labsnet2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['created_at'], 'verbose_name': 'وضعیت درخواست', 'verbose_name_plural': 'وضعیت های درخواست'},
        ),
    ]
