# Generated by Django 4.2.10 on 2025-02-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0073_alter_status_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISOVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible_iso', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'ISO Visibility',
                'verbose_name_plural': 'ISO Visibility',
            },
        ),
    ]
