# Generated by Django 4.2.10 on 2025-02-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0074_isovisibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcertificate',
            name='uncertainty',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='عدم قطعیت'),
        ),
    ]
