# Generated by Django 4.2.10 on 2025-04-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0078_experiment_prepayment_amount_request_has_prepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='total_prepayment_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='مقدار پیش پرداخت'),
        ),
    ]
