# Generated by Django 4.2.10 on 2025-04-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0079_request_total_prepayment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='parameter',
            field=models.ManyToManyField(blank=True, to='lab.parameter', verbose_name='پارامتر'),
        ),
    ]
