# Generated by Django 4.2.10 on 2024-03-12 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EducationalLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('business', 'Business')], default='personal', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, help_text='Enter your address.', max_length=255, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_national_id',
            field=models.CharField(blank=True, help_text='Enter your company national ID.', max_length=11, null=True, unique=True, verbose_name='company national ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_telephone',
            field=models.CharField(blank=True, help_text='Enter your company telephone.', max_length=255, null=True, verbose_name='company telephone'),
        ),
        migrations.AddField(
            model_name='user',
            name='linked_users',
            field=models.ManyToManyField(blank=True, related_name='linked_to_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, help_text='Enter your national ID.', max_length=10, null=True, unique=True, verbose_name='national ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Enter your postal code.', max_length=20, null=True, verbose_name='postal code'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, help_text='Enter your student ID.', max_length=50, null=True, unique=True, verbose_name='student ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='educational_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.educationalfield'),
        ),
        migrations.AddField(
            model_name='user',
            name='educational_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.educationallevel'),
        ),
    ]
