# Generated by Django 4.2.10 on 2024-04-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_accesslevel_role_user_access_level_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.BigIntegerField(default=0, verbose_name='اعتبار'),
        ),
    ]
