# Generated by Django 4.2.10 on 2024-05-06 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='labsnet_grant',
            field=models.BigIntegerField(default=0, verbose_name='گرنت لبزنت'),
        ),
        migrations.AddField(
            model_name='user',
            name='research_grant',
            field=models.BigIntegerField(default=0, verbose_name='گرنت پژوهشی'),
        ),
        migrations.CreateModel(
            name='GrantTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(default=0, help_text='مثدار به ریال', verbose_name='مقدار')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان')),
                ('expiration_date', models.DateField(verbose_name='انقضا')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to=settings.AUTH_USER_MODEL, verbose_name='گیرنده')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
            ],
        ),
        migrations.CreateModel(
            name='GrantRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_amount', models.BigIntegerField(default=0, help_text='مثدار به ریال', verbose_name='مقدار درخواستی')),
                ('approved_amount', models.BigIntegerField(blank=True, default=0, help_text='مثدار به ریال', null=True, verbose_name='مقدار دریافتی')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان')),
                ('expiration_date', models.DateField(verbose_name='انقضا')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('seen', 'Seen'), ('approved', 'Approved')], default='sent', max_length=10)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL, verbose_name='گیرنده')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
            ],
        ),
    ]
