# Generated by Django 4.2.10 on 2024-05-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_labsnet_grant_user_research_grant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslevel',
            name='access_key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Key'),
        ),
        migrations.AddField(
            model_name='role',
            name='access_level',
            field=models.ManyToManyField(blank=True, null=True, to='account.accesslevel'),
        ),
        migrations.AddField(
            model_name='role',
            name='role_key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Key'),
        ),
    ]
