# Generated by Django 4.2.10 on 2024-05-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_accesslevel_access_key_role_access_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='access_level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='access_level',
            field=models.ManyToManyField(to='account.accesslevel'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ManyToManyField(to='account.role'),
        ),
    ]
