# Generated by Django 4.2.10 on 2024-05-11 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_user_access_level_remove_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantrequest',
            name='approved_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تایید'),
        ),
        migrations.AddField(
            model_name='grantrequest',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grant_request', to='account.granttransaction', verbose_name='انقضا'),
        ),
        migrations.AddField(
            model_name='granttransaction',
            name='status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('success', 'Success'), ('failure', 'Failure')], default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='grantrequest',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='انقضا'),
        ),
        migrations.AlterField(
            model_name='grantrequest',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('seen', 'Seen'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='sent', max_length=10),
        ),
        migrations.AlterField(
            model_name='granttransaction',
            name='amount',
            field=models.BigIntegerField(default=0, help_text='مقدار به ریال', verbose_name='مقدار'),
        ),
    ]
