# Generated by Django 4.2.10 on 2024-05-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_grantrequest_approved_datetime_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='OTP',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='granttransaction',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='انقضا'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('username', 'national_id')},
        ),
    ]
