# Generated by Django 4.2.10 on 2024-05-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_user_options_user_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='access_level',
            field=models.ManyToManyField(blank=True, to='account.accesslevel'),
        ),
    ]
