# Generated by Django 4.2.10 on 2024-05-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_role_access_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='OTP',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
