# Generated by Django 4.2.10 on 2024-05-12 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantrequest',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('seen', 'Seen'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='sent', max_length=10),
        ),
    ]
