# Generated by Django 4.2.10 on 2024-05-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_grantrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPserver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=64, null=True)),
                ('password', models.CharField(blank=True, max_length=64, null=True)),
                ('token_expiration', models.DateTimeField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=512, null=True)),
                ('base_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
