# Generated by Django 4.2.10 on 2024-05-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_otpserver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_level',
            field=models.ManyToManyField(blank=True, to='account.accesslevel'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ManyToManyField(blank=True, to='account.role'),
        ),
    ]
