# Generated by Django 4.2.10 on 2024-05-16 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='profile',
            new_name='user',
        ),
    ]
