# Generated by Django 4.2.10 on 2024-05-26 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_rename_profile_notification_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.BigIntegerField(default=0, help_text='مقدار به ریال', verbose_name='مقدار')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='انقضا')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_records', to=settings.AUTH_USER_MODEL, verbose_name='گیرنده')),
            ],
        ),
    ]
