# Generated by Django 4.2.10 on 2024-05-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_grantrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, help_text='Enter your company name.', max_length=150, null=True, verbose_name='company name'),
        ),
    ]
