# Generated by Django 4.2.10 on 2024-07-08 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_user_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantrequest',
            name='approved_grant_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.grantrecord'),
        ),
        migrations.AddField(
            model_name='granttransaction',
            name='grant_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.grantrecord'),
        ),
        migrations.AlterField(
            model_name='grantrequest',
            name='requested_amount',
            field=models.BigIntegerField(default=0, help_text='مقدار به ریال', verbose_name='مقدار درخواستی'),
        ),
    ]
