# Generated by Django 4.2.10 on 2024-07-08 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_grantrequest_approved_grant_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantrequest',
            name='approved_amount',
            field=models.BigIntegerField(blank=True, default=0, help_text='مقدار به ریال', null=True, verbose_name='مقدار دریافتی'),
        ),
        migrations.AlterField(
            model_name='grantrequest',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grant_request', to='account.granttransaction', verbose_name='گرنت تراکنش'),
        ),
    ]
