# Generated by Django 4.2.10 on 2024-09-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_grantrequest_approved_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_sharif_student',
            field=models.BooleanField(default=False, verbose_name='دانشجوی شریف'),
        ),
    ]
