# Generated by Django 4.2.10 on 2024-09-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_user_is_sharif_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_partner',
            field=models.BooleanField(default=False, verbose_name='شرکت همکار'),
        ),
    ]
