# Generated by Django 4.2.10 on 2024-09-28 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_user_is_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'دپارتمان',
                'verbose_name_plural': 'دپارتمان\u200cها',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='labsnet_grant',
        ),
        migrations.RemoveField(
            model_name='user',
            name='research_grant',
        ),
        migrations.AddField(
            model_name='user',
            name='company_economic_number',
            field=models.CharField(blank=True, help_text='Enter your company economic number.', max_length=25, null=True, unique=True, verbose_name='company economic number'),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, help_text='Enter your company telephone.', max_length=255, null=True, verbose_name='telephone'),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='account.department', verbose_name='دپارتمان'),
        ),
    ]
