# Generated by Django 4.2.10 on 2024-10-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_department_remove_user_labsnet_grant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantrequest',
            name='remaining_amount',
            field=models.BigIntegerField(blank=True, default=0, help_text='مقدار به ریال', null=True, verbose_name='مقدار باقی مانده'),
        ),
    ]
