# Generated by Django 4.2.10 on 2024-11-03 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_grantrequest_remaining_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'دانشکده', 'verbose_name_plural': 'دانشکده ها'},
        ),
    ]
