# Generated by Django 4.2.10 on 2024-11-17 11:17

import apps.account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_alter_department_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, error_messages={'blank': 'کد ملی نمی\u200cتواند خالی باشد.', 'required': 'کد ملی اجباری است.'}, help_text='Enter your national ID.', max_length=10, null=True, unique=True, verbose_name='national ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'blank': 'نام کاربری نمی\u200cتواند خالی باشد.', 'required': 'نام کاربری اجباری است.'}, help_text='Required. Enter a valid phone number. Example: +989123456789', max_length=150, unique=True, validators=[apps.account.models.PhoneValidator()], verbose_name='username'),
        ),
    ]
