# Generated by Django 4.2.10 on 2024-11-17 11:32

import apps.account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_alter_user_national_id_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, error_messages={'blank': 'کد ملی نمی\u200cتواند خالی باشد.', 'invalid': 'کد ملی وارد شده معتبر نیست.', 'max_length': 'کد ملی باید حداکثر 10 رقم باشد.', 'min_length': 'کد ملی باید حداقل 10 رقم باشد.', 'required': 'کد ملی اجباری است.', 'unique': 'کاربری با این کد ملی وجود دارد.'}, help_text='Enter your national ID.', max_length=10, null=True, unique=True, verbose_name='national ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'blank': 'نام کاربری نمی\u200cتواند خالی باشد.', 'invalid': 'نام کاربری وارد شده معتبر نیست.', 'max_length': 'نام کاربری نباید بیشتر از 150 کاراکتر باشد.', 'min_length': 'نام کاربری باید حداقل 3 کاراکتر باشد.', 'required': 'نام کاربری اجباری است.', 'unique': 'کاربری با این نام کاربری وجود دارد.'}, help_text='Required. Enter a valid phone number. Example: +989123456789', max_length=150, unique=True, validators=[apps.account.models.PhoneValidator()], verbose_name='username'),
        ),
    ]
