# Generated by Django 4.2.10 on 2024-11-17 13:15

import apps.account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_alter_user_national_id_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'blank': 'شماره نمی\u200cتواند خالی باشد.', 'invalid': 'شماره وارد شده معتبر نیست.', 'max_length': 'شماره نباید بیشتر از 150 کاراکتر باشد.', 'min_length': 'شماره باید حداقل 3 کاراکتر باشد.', 'required': 'شماره اجباری است.', 'unique': 'کاربری با این شماره وجود دارد.'}, help_text='Required. Enter a valid phone number. Example: +989123456789', max_length=150, unique=True, validators=[apps.account.models.PhoneValidator()], verbose_name='username'),
        ),
    ]
