# Generated by Django 4.2.10 on 2024-12-29 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantRequestTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_amount', models.BigIntegerField(default=0, verbose_name='مقدار استفاده شده')),
                ('remaining_amount_before', models.BigIntegerField(default=0, verbose_name='مقدار باقی مانده قبل از تراکنش')),
                ('remaining_amount_after', models.BigIntegerField(default=0, verbose_name='مقدار باقی مانده بعد از تراکنش')),
                ('transaction_type', models.CharField(choices=[('use', 'Use'), ('revoke', 'Revoke')], max_length=10, verbose_name='نوع تراکنش')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='زمان تراکنش')),
                ('grant_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.grantrequest', verbose_name='درخواست گرنت')),
            ],
            options={
                'verbose_name': 'تراکنش گرنت',
                'verbose_name_plural': 'تراکنش\u200cهای گرنت',
            },
        ),
    ]
