# Generated by Django 4.2.10 on 2024-12-29 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_grantrequesttransaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GrantRequestTransaction',
        ),
    ]
