# Generated by Django 4.2.10 on 2025-01-13 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_delete_grantrequesttransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabsnetCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labsnet_id', models.CharField(max_length=255, unique=True, verbose_name='شناسه لبزنت')),
                ('amount', models.CharField(max_length=255, verbose_name='مبلغ کل')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
                ('remain', models.CharField(max_length=255, verbose_name='مبلغ باقی\u200cمانده')),
                ('percent', models.CharField(max_length=10, verbose_name='درصد استفاده\u200cشده')),
                ('title', models.TextField(verbose_name='عنوان اعتبار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labsnet_credits', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اعتبار لبزنت',
                'verbose_name_plural': 'اعتبارهای لبزنت',
            },
        ),
    ]
