# Generated by Django 4.2.10 on 2025-01-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_labsnetcredit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_national_id',
            field=models.CharField(blank=True, help_text='Enter your company national ID.', max_length=15, null=True, unique=True, verbose_name='company national ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'blank': 'شماره نمی\u200cتواند خالی باشد.', 'invalid': 'شماره وارد شده معتبر نیست.', 'max_length': 'شماره نباید بیشتر از 150 کاراکتر باشد.', 'min_length': 'شماره باید حداقل 3 کاراکتر باشد.', 'required': 'شماره اجباری است.', 'unique': 'کاربری با این شماره وجود دارد.'}, help_text='Required. Enter a valid phone number. Example: +989123456789', max_length=150, unique=True, verbose_name='username'),
        ),
    ]
