# Generated by Django 4.2.10 on 2025-04-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_alter_user_national_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, error_messages={'blank': 'کد ملی نمی\u200cتواند خالی باشد.', 'invalid': 'کد ملی وارد شده معتبر نیست.', 'max_length': 'کد ملی باید حداکثر 10 رقم باشد.', 'min_length': 'کد ملی باید حداقل 10 رقم باشد.', 'required': 'کد ملی اجباری است.', 'unique': 'کاربری با این کد ملی وجود دارد.'}, help_text='Enter your national ID.', max_length=15, null=True, verbose_name='national ID'),
        ),
    ]
